import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from 'redux/store';
import { fetchCount, fetchMovieList } from './movieListAPI';

export interface MovieListState {
  value: number;
  status: 'idle' | 'loading' | 'failed';
}

const initialState: MovieListState = {
  value: 0,
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const incrementAsync = createAsyncThunk('movieList/fetchCount', async (amount: number) => {
  const response = await fetchCount(amount);
  // The value we return becomes the `fulfilled` action payload
  return response.data;
});

export const fetchMovieListAsync = createAsyncThunk('movieList/fetchMovieList', async () => {
  const response = await fetchMovieList();
  console.log('fetchMovieListAsync', response);
  return response;
});

export const movieListSlice = createSlice({
  name: 'movieList',
  initialState,
  reducers: {
    getMovieList: (state) => {},
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.value += action.payload;
      })
      .addCase(incrementAsync.rejected, (state) => {
        state.status = 'failed';
      });
  },
});

// Actions
export const { getMovieList, increment, decrement, incrementByAmount } = movieListSlice.actions;

// Selectors
export const selectCount = (state: RootState) => state.movieList.value;
export const selectMovieList = (state: RootState) => state.movieList.value;

// Reducers
export default movieListSlice.reducer;
